services:
  ? adp-test1
  : build:
      context: .
      target: production
    image: adp-test1
    container_name: adp-test1
    environment:
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      APPINSIGHTS_CLOUDROLE: adp-test1-local